issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: justif-dev
    secret: justif-dev-secret
    name: Justif (dev)
    redirectURIs:
      - http://localhost:3000/api/auth/oidc/callback

enablePasswordDB: true
staticPasswords:
  - email: admin@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZdwkci/8q."
    username: Admin
    userID: "00000000-0000-0000-0000-000000000001"
  - email: user@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZdwkci/8q."
    username: User
    userID: "00000000-0000-0000-0000-000000000002"
